name: CI

on:
  push
  workflow_dispatch:
    inputs:
      os:
        required: true
        default: 'ubuntu-latest'
        description: 'OS. E.g., ubuntu-latest, windows-latest, macos-latest'
      container:
        required: false
        description: 'Container (only for Linux). E.g., conanio/gcc9-arm7hf'
      package:
        required: true
        description: 'Package. E.g., boost/1.77.0@'
      build:
        required: true
        default: 'always'
        description: 'Build or cache?. E.g., always, never, missing'

jobs:
  build1:
    if: github.event.inputs.container != ''
    runs-on: ubuntu-latest
    steps:
      - run: docker run --rm -t ${{ github.event.inputs.container }} conan --build=${{ github.event.inputs.build }} install ${{ github.event.inputs.package }}

  build2:
    if: github.event.inputs.container == ''
    runs-on: github.event.inputs.os
    steps:
      - run: pip3 install conan
      - run: conan --build=${{ github.event.inputs.build }} install ${{ github.event.inputs.package }}
