name: CI

on:
  push
#  workflow_dispatch:
#    inputs:
#      package:
#        required: true
#        description: 'E.g., boost/1.77.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip3 install conan
          conan install boost/1.77.0@ --build
#      - run: |
#          docker run --rm -t conanio/gcc9 conan install boost/1.77.0@ --build
#      - run: conan install ${{ github.event.inputs.package }} --build=missing
       #    runs-on: ubuntu-latest
        #
        #    steps:
        #      - uses: actions/checkout@v2
        #
        #      - name: Run a one-line script
      #        run: echo Hello, world!
