name: Proof of Conan

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: echo here we go
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: conan-io/conan-center-index

      - uses: actions/upload-artifact@v1
        with:
          name: repo
          path: recipes/boost

  _:
    runs-on: windows-latest
    needs: checkout
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: repo
      - run: du -a
        shell: bash
      - run: mv repo/all/* .
        shell: bash
      - run: pip3 install conan
      - name: 'Install toolchain'
        run: conan install "mingw-w64/8.1@" -g virtualenv
      - name: 'Enable toolchain'
        run: |
          source activate.sh
          which g++
          conan profile new default --detect --force
          sed -i 's/\(.build_requires.\)/\1\nmingw-w64/8.1/' ~/.conan/profiles/default
          conan profile show default
        shell: bash
      - run: conan create . boost/1.71.0@ --build=missing
