name: Ultimate builder

on:
  workflow_dispatch:
    inputs:
      targets:
        required: true
        description: 'JSON of all your targets'


jobs:
  _:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(github.event.inputs.targets)}}

    steps:
      - run: echo ${{ matrix }}
      - run: |
          # https://unix.stackexchange.com/a/498744
          case "${{ matrix.conancmd }}" in
            ("" | *[!abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890./@\-\ =+\'_:]*)
              echo "NOT ALLOWED" && exit 1;;
            (*)
              echo "::set-output name=test::${{ matrix.conancmd }}";;
          esac
        shell: bash
      - run: pip3 install conan
      - name: 'Install toolchain'
        if: ${{ matrix.toolchain != '' }}
        run: conan install "${{ matrix.toolchain }}" -g virtualenv
      - name: 'Enable toolchain in Windows'
        if: ${{ matrix.toolchain != '' && matrix.toolchainos == 'windows' }}
        run: . .\activate.ps1
      - name: 'Enable toolchain in Linux'
        if: ${{ matrix.toolchain != '' && matrix.toolchainos == 'lunix' }}
        run: source activate.sh
      - name: 'Reset profile'
        if: ${{ matrix.toolchain != '' }}
        run: conan profile new default --detect --force
      - run: which g++
      - run: conan install ${{ matrix.conancmd }}
