name: Ultimate builder

on:
  workflow_dispatch:
    inputs:
      targets:
        required: true
        description: 'JSON of all your targets'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(github.event.inputs.targets)}}

    steps:
      - run: echo ${{ matrix }}
